---
- name: Include Ubuntu Playbook
  ansible.builtin.include_tasks:
    file: ubuntu-playbook.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Include Redhat Playbook
  ansible.builtin.include_tasks:
    file: redhat-playbook.yml
  when: ansible_os_family == 'RedHat'
