---
- name: Include Ubuntu Playbook
  ansible.builtin.include_tasks:
    file: ubuntu-playbook.yml
    when: ansible_facts['os_family'] == "Ubuntu"

- name: Include Redhat Playbook
  ansible.builtin.include_tasks:
    file: redhat-playbook.yml
    when: ansible_facts['os_family'] == "Redhat"
