---
# tasks file for user
- name: Yum update the system
  ansible.builtin.dnf:
    update_cache: yes

- name: "Add user"
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "/bin/bash"
    create_home: true
    groups: wheel
    append: true
  loop: "{{ users }}"

- name: "Inject SSH Key"
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
    exclusive: true
    state: present
  loop: "{{ users }}"

- name: "Passwordless wheel"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"

- name: Disable IPv6 for the default interface
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.eth0.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: "RedHat | Disable IPv6"
  block:
    - name: "RedHat | IPv6 Status"
      ansible.builtin.shell: |
        #!/bin/bash
        grubby --info DEFAULT | grep "ipv6.disable=1"
        echo $?
      register: ipv6_status

    - name: "RedHat | Disable IPv6"
      ansible.builtin.shell: |
        grubby --args ipv6.disable=1 --update-kernel DEFAULT
      when: ipv6_status.stdout != "0"
# - name: Reboot machine and send a message
#   ansible.builtin.reboot:
#     msg: "Rebooting machine in 5 seconds"
