---
# tasks file for user

- name: "Add user"
  ansible.builtin.user:
    name: "{{item.name}}"
    shell: "/bin/bash"
    create_home: true
    groups: wheel
    append: true
  loop: "{{users}}"
  when: ansible_facts['os_family'] == "Redhat"

- name: "Inject SSH Key"
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
    exclusive: true
    state: present
  loop: "{{users}}"

- name: "Passwordless wheel"
  ansible.builtin.lineinfile:
    path: /etc/wheelers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD:ALL"
    validate: "viwheel -cf %s"
