---
# tasks file for user

- name: "apt-get update"
  ansible.builtin.apt:
    update_cache: yes

- name: "Add user"
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "/bin/bash"
    create_home: true
    groups: sudo
    append: true
  loop: "{{ users }}"

- name: "Inject SSH Key"
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
    exclusive: true
    state: present
  loop: "{{ users }}"

- name: "Passwordless Sudo"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"

- name: Disable IPv6 for the default interface
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.eth0.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Ensure ipv6.disable=1 is in GRUB_CMDLINE_LINUX
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX="
    line: 'GRUB_CMDLINE_LINUX="ipv6.disable=1"'
    backrefs: no

- name: Update GRUB configuration
  command: grub-mkconfig -o /boot/grub/grub.cfg

- name: Reboot machine and send a message
  ansible.builtin.reboot:
    msg: "Rebooting machine in 300 seconds"
